### ISSUE TITLE
Only health endpoint uses correct protocol (https), when registering with secure port

### ISSUE THREAD

**Issue by crea1** [codecentric/spring-boot-admin#1130]
Hi, thank you for taking the time to look at this. Our setup is that we have Eureka which applications registers to using discovery client. The applications is behind a reverse proxy, to enable ssl. Only port 443 is open. Applications in eureka is registered with IP, and have the config

```yaml
eureka:
  client:
    service-url:
      defaultZone: ${eureka.url}
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    prefer-ip-address: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
```

In SBA admin the applications are registered as for instance `https://10.0.75.2:443/`, and reports them as UP. But when trying to look at details, the only thing showing is the information from `https://10.0.75.2:443/actuator/health`. Everything else returns a 502 bad gateway, coming from our nginx reverse proxy. Looking at the SBA endpoint `/instances/5d0e605b7ad9` we can see that it only sets https on the health endpoint. Here's a snippet:
```json
{
  "id": "5d0e605b7ad9",
  "version": 2,
  "registration": {
    "name": "Application",
    "managementUrl": "https://10.0.75.2:443/actuator",
    "healthUrl": "https://10.0.75.2:443/actuator/health",
    "serviceUrl": "https://10.0.75.2:443/",
    "source": "discovery",
    "metadata": {
    }
  },
  "endpoints": [
    {
      "id": "resume",
      "url": "http://10.0.75.2/actuator/resume"
    },
    {
      "id": "httptrace",
      "url": "http://10.0.75.2/actuator/httptrace"
    },
    {
      "id": "caches",
      "url": "http://10.0.75.2/actuator/caches"
    },
    {
      "id": "restart",
      "url": "http://10.0.75.2/actuator/restart"
    },
    {
      "id": "loggers",
      "url": "http://10.0.75.2/actuator/loggers"
    },
    {
      "id": "health",
      "url": "https://10.0.75.2:443/actuator/health"
    }]
}
```
Notice that only "health" uses https. 

We are using 
Spring Boot: 2.1.3
Spring Boot Admin: 2.1.3
