### ISSUE TITLE
how to use JWT token for spring-boot-admin client

### ISSUE THREAD

**Issue by sjlmsj** [codecentric/spring-boot-admin#1241]
My app use JWT token in http header to send api request. When I integrate the sprint-boot-admin, it said "Fetching metrics index failed. Request failed with status code 401". Does anyone have idea how to solve that?
Here is part of JWT code and application.yml:
```
@Configuration
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
	
	private UserDetailsService userDetailsService;
	
	private BCryptPasswordEncoder bCryptPasswordEncoder;

	@Value("#{'${spring.websocket.domains}'.split(',')}")
	public List<String> domains;

	public WebSecurityConfig(UserDetailsService userDetailsService, BCryptPasswordEncoder bCryptPasswordEncoder) {
		this.userDetailsService = userDetailsService;
		this.bCryptPasswordEncoder = bCryptPasswordEncoder;
	}

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http.csrf().ignoringAntMatchers("/druid/*");
		http.cors().and().csrf().disable();
		http.addFilterBefore(new CORSFilter(domains), ChannelProcessingFilter.class);
		http.addFilterBefore(new JWTAuthenticationFilter(), UsernamePasswordAuthenticationFilter.class);
		http.addFilterBefore(new JWTLoginFilter(authenticationManager()), UsernamePasswordAuthenticationFilter.class);
		http.authorizeRequests().anyRequest().permitAll();
	}

	@Override
	public void configure(AuthenticationManagerBuilder auth) throws Exception {
		auth.userDetailsService(userDetailsService).passwordEncoder(bCryptPasswordEncoder);
	}
}
```
My application.yml: 
```
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8769

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
```
