### ISSUE TITLE
allow scheme configuration for Cloudfoundry

### ISSUE THREAD

**Issue by imod** [codecentric/spring-boot-admin#1269]
I'm running SBA and all client apps on cloudfoundry. The configuration does work, but I'm not able to configure SBA to use HTTPS to connect to the clients. 

This is what I have configured:

```
spring:
  boot:
    admin:
      client:
        instance:
          metadata:
            applicationId: ${vcap.application.application_id}
            instanceId: ${vcap.application.instance_index}
            user.name: xxxxx@zzzz.com
            user.password: ppppppppppppp
        password: ${spring.cloud.config.password}
        service-url: https://xx-yyyy-domi-ci.scapp.io
        url:
        - https://oooo.zzzz.com/admin
        username: ${spring.cloud.config.username}
```

This is what the journal in SBA shows:
```
{
    "registration": {
        "name": "api",
        "managementUrl": "http://xx-yyyy-ci.scapp.io/actuator",
        "healthUrl": "http://xx-yyyy-ci.scapp.io/actuator/health",
        "serviceUrl": "http://xx-yyyy-ci.scapp.io/",
        "source": "http-api",
        "metadata": {
            "user.name": "xxxxx@zzzz.com",
            "instanceId": "0",
            "applicationId": "c77c8622-34e3-410d-904a-edec8fc539c2",
            "user.password": "******",
            "startup": "2019-10-01T07:45:32.218294Z"
        }
    }
}
```
as you can see the `service-url` is set to https://xx-yyyy-domi-ci.scapp.io in the config (-domi- is added on purpose to be wrong, so I can see it causing an error once it gets picked up) - but it is not reflected in the registration journal in SBA.
And this are the real urls displayed (and used) in the application details view in SBA:

service: http://xx-yyyy-ci.scapp.io/
management: http://xx-yyyy-ci.scapp.io/actuator
health: http://xx-yyyy-ci.scapp.io/actuator/health

Just to be clear, the configuration does work, and the status of the app is shown correctly - also all actuators are shown correct in SBA. But it is not picking up the configuration I give it, HTTPS is not used. It also does not make any difference if I use `service-url` or `service-base-url`.

As running I'm on CloudFoundry, `CloudFoundryApplicationFactory` is active and It uses the uris from `vcap.application.*` with a fixed `http` scheme.

In my opinion there are two things that should be possible:

1. allow the schema used by `CloudFoundryApplicationFactory` to be configured - this would easy the configuration a lot and make it very flexible, but also still automatically pickup the uris from `vcap.application.*`
1. it should be possible to overwrite  `service-url` ans `service-base-url` to allow full control on how SBA server connects to the client
