### ISSUE TITLE
Applications show 401 in kubernetes environment with secure health EndPoint.

### ISSUE THREAD

**Issue by Macrame** [codecentric/spring-boot-admin#1325]
** Bug report **
### Describe the bug
Fail to fetch the live health status with spring-cloud Greenwich.SR4 and spring-boot 2.1.6 in kubernetes cluster.

#### Detail information

I have an application using Spring Boot Admin with the following dependencies.

Spring Boot 2.1.6.RELEASE
Spring Cloud Dependencies Greenwich.SR4 
```
ext {
    spring_boot_adminVersion = '2.1.6'
}
dependencies {
    compile('org.springframework.boot:spring-boot-starter-actuator')
    compile "org.springframework.boot:spring-boot-starter-security"
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.springframework.cloud:spring-cloud-starter-config")
    compile('org.springframework.cloud:spring-cloud-starter-netflix-eureka-client')
    compile('org.springframework.cloud:spring-cloud-starter-kubernetes')
    compile("de.codecentric:spring-boot-admin-starter-server:${spring_boot_adminVersion}")
}
```
The kubernetes is disabled in development env but eureka was diabled in production env.
It works well in development environment.
```
spring:
    main:
        allow-bean-definition-overriding: true
    cloud:
        config:
            allowOverride: true
            overrideNone: true
        stream:
            default-binder: rabbit
        kubernetes:
            enabled: false
            discovery:
                enabled: false
    security:
        user:
            name: spring_admin
            password: $2a$10$0Y6Ro.vevMFX/YsPOBySEuEALBhwgLhTci.Bx2fiRidIWIT/ihaMu
        basic:
            enabled: true
        ignored: /api/v1/spans,/turbine.stream,/hystrix.stream,/v2/api-docs
    sleuth:
        sampler:
            percentage: 1
        scheduled:
            skipPattern: "org.springframework.cloud.netflix.hystrix.stream.HystrixStreamTask"
    zipkin:
        sender:
            type: kafka
    kafka:
        bootstrap-servers: kafka-server:9092
    autoconfigure:
        exclude: 
            #- org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
            - org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration
eureka:
    instance:
        preferIpAddress: true
        metadata-map:
            user:
                name: ${security.user.name}
                password: peony_system
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
```

Now I can login the spring boot admin in production environment but all the services are DOWN in the application list. It always shows an Authorization dialog every time when I click each service to display the detail information. Apparently, it has the 401 status in the detail panel.
This is the configuration item in production environment(kubernetes).
```
spring:
    cloud:
        config:
            allowOverride: true
            overrideNone: true
        stream:
            default-binder: rabbit
    security:
        user:
            name: spring-boot-admin
            password: $2a$10$g0h4cD95vqMjrwXb87***(encrypted password)
        basic:
            enabled: true
        ignored: /turbine.stream,/hystrix.stream
management:
    info:
        git:
            mode: simple
    endpoints:
        web:
          exposure:
              include: "*"  
    endpoint:
        health:
            show-details: ALWAYS
        shutdown:
            enabled: false
```
And the configuration for Spring Boot Admin:
```
loging:
    level:
        de.codecentric.boot.admin.server.cloud: DEBUG
spring:
    boot:
        admin:
            ui:
                public-url: https://spring-dashboard-test.xxxxxxx.com
            client:
                instance:
                    health-url: /actuator/health
                    metadata:
                        user.name: spring-boot-admin
                        user.password: ****
            discovery:
                services: "*service*"
                ignored-services: kafka-hs,zk-cs,zk-hs,mysql-master,mongo-master,kafka-server
```
It starts correctly but all the applications are **DOWN**.

**Comment by Macrame** [comment]
There are only SBA Client and Eureka client discovery config in [Securing Client Actuator Endpoints](https://codecentric.github.io/spring-boot-admin/2.1.6/#_securing_client_actuator_endpoints).
I also read the [Samples](https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples). There is no project to demonstrate the secure health end point in Kubernetes environment.

Below is the source code snippet in the default BasicAuthHttpHeaderProvider.
```
	@Override
	public HttpHeaders getHeaders(Instance instance) {
		String username = instance.getRegistration().getMetadata().get("user.name");
		String password = instance.getRegistration().getMetadata().get("user.password");

		HttpHeaders headers = new HttpHeaders();

		if (StringUtils.hasText(username) && StringUtils.hasText(password)) {
			headers.set(HttpHeaders.AUTHORIZATION, encode(username, password));
		}

		return headers;
	}
```
I don't known where can the metadata be obtained in kubernetes.

**Comment by Macrame** [comment]
Basic Authorization work well in kubernetes' livenessProbe.
```
apiVersion: apps/v1
kind: Deployment
   ...
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8012
            scheme: HTTP
            httpHeaders:
              - name: Authorization
                value: Basic c3ByaW5nLWJv***********WRtaW4=
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8012
            scheme: HTTP
            httpHeaders:
              - name: Authorization
                value: Basic c3ByaW5nLWJv***********WRtaW4=
          initialDelaySeconds: 120
          timeoutSeconds: 5
```
