### ISSUE TITLE
No Info Provided Problem

### ISSUE THREAD

**Issue by zjy5755202** [codecentric/spring-boot-admin#1326]
I am using sping boot admin 2.1.5.

My yml looks like this
```
server:
  port: 9004

spring:
  boot:
    admin:
      client:
        url: "http://localhost:9004"

  application:
    name: AdminServer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    #
    registry-fetch-interval-seconds: 5
  instance:
    health-check-url-path: actuator/health
    status-page-url-path: actuator/info
    #
    lease-renewal-interval-in-seconds: 10


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  level:
    com.zjy: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
```

I can see health in admin web ui,but i can not see info 
It looks like this
![}T A5`VOHXU{RP9R_$5U`D1](https://user-images.githubusercontent.com/32031556/70588385-84685400-1c07-11ea-8f43-067333d0422e.png)

Can anyone help me to solve the problem?
Thanks a lot.
