### ISSUE TITLE
Can not fetch the config server or can not fetch the config from config server

### ISSUE THREAD

**Issue by andyzhaozhao** [codecentric/spring-boot-admin#1336]
In Spring Cloud G .Everthing runs well. But in Spring Cloud Hoxton.SR1.Spring Boot 2.2.1., there is  a bug i think:

I have config the SBA fetch configs from conig server, like that:
```
...
spring:
  profiles:
    active: test
....
---
spring:
  profiles: test
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 15
        max-interval: 3000
        multiplier: 1.3
      profile: test
      label: dev
      discovery:
        enabled: false
        service-id: tdf-cloud-config
eureka:
  client:
    service-url:
      defaultZone: "http://appadmin:app123456@192.168.70.40:8761/eureka"
.....
```
But the SBA did not  fetch the correct config server from 192.168.70.40 . the error logs from console:
![image](https://user-images.githubusercontent.com/7730080/71471897-e500af00-280b-11ea-8074-f740053522fc.png)
It always fetch config from `localhost`
