### ISSUE TITLE
External views not working

### ISSUE THREAD

**Issue by Ask149** [codecentric/spring-boot-admin#1343]
I tried to use the properties as mentioned
```
spring:
  boot:
    admin:
      ui:
        external-views:
          - label: "🚀"
            url: http://codecentric.de
            order: 2000
```
But, I am unable to see any changes in the UI and no external link is visible.

**Comment by DhavalShewale** [comment]
@Ask149 This works fine for me. Which version of SBA are you using?

**Comment by Ask149** [comment]
@DhavalShewale I am using 2.1.6 Version for SBA.
Could you please share me the exact location where the new label gets positioned?

**Comment by DhavalShewale** [comment]
It adds the external view link on the header right next to ````About````. This works fine for SBA 2.2.x. I had not explored this feature with SBA 2.1.x.

It is less likely but the symbol might not be displayed due to rendering issues. Trying using a text label instead for the external view, if you are still unable to locate it.

**Comment by DhavalShewale** [comment]
This feature is not available as part of `SBA 2.1.6`. You can refer the documentation for this version [here](https://codecentric.github.io/spring-boot-admin/2.1.6/).

**Comment by DhavalShewale** [comment]
@joshiste `iframe=true` does not work for me. Can you pls confirm if below config is correct.

````
spring:
  boot:
    admin:
      ui:
        external-views:
          - label: "🚀"
            url: http://codecentric.de
            order: 2000
            iframe: true
````
