### ISSUE TITLE
Services appear DOWN when they are UP - Health url is okay in some places, in others not

### ISSUE THREAD

**Issue by cgew85** [codecentric/spring-boot-admin#1364]
Hello!
I have an issue with the way urls are composited. 

![Spring Boot Admin Issue](https://user-images.githubusercontent.com/13754436/75319127-52f93f00-586c-11ea-8118-39146f08bb7b.png)

The urls at the top are all fine and working, the url that is used inside the health tab is wrong. It uses the right url but attaches an ip at the end.

The SBA logs show this error:
`
io.netty.channel.ConnectTimeoutException: connection timed out: <url removed >/10.58.124.147:80
`

application.yml (SBA):
```
server:
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 512
  servlet:
    context-path: /app/<path removed>/
  use-forward-headers: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    ldap:
      enabled: false

spring:
  boot:
    admin:
      ui:
        public-url: /
      context-path: /
      instance-proxy:
        ignored-headers: ""
```

The client's config:

```
...
  boot:
    admin:
      client:
        url: ${spring_boot_admin_server_url}
        api-path: /app/<path removed>/instances/
        instance:
          metadata:
            user.name: ${tu_access_USER}
            user.password: ${tu_access_PASSWORD}
          service-base-url: ${service_url}
management:
  endpoints:
    web:
      exposure:
        include: "*"
```

How come the url is composited right in some cases and in other it's not?

Spring Boot Version 2.1.8.RELEASE
Spring Boot Admin Version 2.1.6

Best wishes and thanks in advance :)
