### ISSUE TITLE
Is it possible to enable custom view according to Spring profile?

### ISSUE THREAD

**Issue by seolmin-lee** [codecentric/spring-boot-admin#1385]
For example:
```js
SBA.use({
  install({viewRegistry}) {
    viewRegistry.addView({
      name: 'custom',  
      path: '/custom', 
      component: custom, 
      label: 'Custom', 
      order: 1000, 
      isEnabled: ({profiles}) => profiles.include('develop') 
    });
  }
});
```
Is there another way or is it possible to apply?

**Comment by joshiste** [comment]
As of now it's not that easy like you describe. 
But here are two suggestions that might work for you:

if the profile is set in the client application, you could just activate/deactivate an actuator endpoint depending on the profile and the test can check whether it's present - that is what SBA does for many views.

if the profile is set in the SBA server you could try to enable/disable the plugin, by not serving it to the ui. You could try to customize the [UiController](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiAutoConfiguration.java#L81) so that it doesn't ship the view.

Currently I think the best approach to this problem would be to make the isEnabled method of the views to support promises so that you could do http requests in there.

**Comment by seolmin-lee** [comment]
@joshiste thank you for the reply.

I did it the following way.
```yaml
---
spring:
  profiles: develop
  boot:
    admin:
      ui:
        extension-resource-locations:  # ... Extensions to be used in develop

---
spring:
  profiles: production
  boot:
    admin:
      ui:
        extension-resource-locations:  # ... Extensions to be used in production
```
What do you think of this solution?
