### ISSUE TITLE
关于Admin被监控和两个实例副本的bug

### ISSUE THREAD

**Issue by feiquan666** [codecentric/spring-boot-admin#1392]
![image](https://user-images.githubusercontent.com/42441073/78889870-20f81100-7a97-11ea-8d19-490fb9d24231.png)
问题描述：
#### 2 .我只向AdminServer注册了名为：eureka-client0 的客户端，但应用列表时而显示两个 eureka-client0的项目，时而显示1个，其中另一个的名字是大写的，如图所示。

PS：以下是我的Server和client的yaml配置
```
server:
  port: 9857
spring:
  application:
    name: eureka-admin
  boot:
    admin:
      client:
        enabled: false # 是否注册，默认true
      ui:
        brand: "<img src='' alt=''>"
        title: "微服务监控"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8848/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*' # 生产环境慎用*
  endpoint:
    health:
      show-details: ALWAYS`

server:
  port: 9858
spring:
  application:
    name: eureka-client0
  boot:
    admin:
      client:
        url: http://localhost:9857 # SBA服务器地址,多个地址以逗号隔开
        register: true # 只向一台SBA服务器注册,如果SBA宕机，则向其他的SBA注册，默认为true
        instance:
          name: ${spring.application.name} # 要注册客户端名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8848/eureka/
  instance:
    instance-id:
      ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
```
