### ISSUE TITLE
SimpleDiscoveryClient requires EurekaServiceInstance

### ISSUE THREAD

**Issue by dersvenhesse** [codecentric/spring-boot-admin#1448]
When setting up SBA using the SimpleDiscoveryClient with static setup, an error occurs during startup:

```
2020-06-05 10:00:13.597 ERROR 19452 --- [           main] d.c.b.a.s.c.d.InstanceDiscoveryListener  : Couldn't register instance for discovered instance (serviceId=test, instanceId=null, url= http://instance2.intern:8080)

java.lang.IllegalArgumentException: serviceInstance must be of type EurekaServiceInstance: org.springframework.cloud.client.discovery.simple.SimpleDiscoveryProperties$SimpleServiceInstance
```

Since used examples provided in the documentation, I assume there is something missing or undocumented (since SBA is not even trying to connect to the client, I didn't start one or configured my own one). Or am I missing something?

Here is a minimal setup to reproduce:

Application.java
```
@Configuration
@EnableAutoConfiguration
@EnableAdminServer
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
    
}
```

pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.0.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>com.tryout</groupId>
    <artifactId>admin</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>admin</name>

    <properties>
        <java.version>14</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-server</artifactId>
            <version>2.2.3</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>
</project>
```

application.yaml ([similar to documentation](https://codecentric.github.io/spring-boot-admin/current/#spring-cloud-discovery-static-config))
```
server.port: 8081

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            test:
              - uri: http://instance1.intern:8080
                metadata:
                  management.context-path: /actuator
              - uri: http://instance2.intern:8080
                metadata:
                  management.context-path: /actuator
```
