### ISSUE TITLE
SpringBootAdmin configuration behind SpringCloudGateway

### ISSUE THREAD

**Issue by dassebi** [codecentric/spring-boot-admin#1492]
My Spring-Boot-Admin-service is running in a docker-container behind a Spring-Gateway. For this I configured the public-url this way:

```
spring:
  boot:
    admin:
      ui:
        public-url: "https://myAppname.intranet.cnb/monitoring/"
```
My problem now is, that spring-admin by default adds a port (in my case "8080"), if it is omitted. This results in a URL

`https://myAppname.intranet.cnb:8080/monitoring/`

A port in this public-url does not work for me. Any idea how to configure this public-url without a port? When I run the services in my local environment (where the gateway runs on localhost:8000) everything works fine with a configuration of "public-url: "http://localhost:8000/monitoring"

I think this is a very common problem, but I don't see the (probably obvious) solution.

**Comment by welsh** [comment]
So I actually just managed to get this working myself, what I've done is on the Spring Cloud Gateway side on the `application.yml` is:

```
spring:
  cloud:
    gateway:
      routes:
        - id: spring-boot-admin
          uri: lb://qa-spring-boot-admin
          predicates:
            - Path=/monitoring/boot/**
```
And then on the Spring Boot Admins side I've setup my `application.yml` to have the following set:
```
server:
  forward-headers-strategy: native

spring:
  boot:
    admin:
      context-path: /monitoring/boot
      ui:
        public-url: https://myAppname.intranet.cnb/monitoring/boot/
```
With the following Filter added
```
@Configuration
public class ReverseProxyFilter {

    @Bean
    ForwardedHeaderFilter forwardedHeaderFilter() {
        return new ForwardedHeaderFilter();
    }

}
```
Which seems to have things working properly.
