### ISSUE TITLE
public-url not used with Spring security

### ISSUE THREAD

**Issue by akuma8** [codecentric/spring-boot-admin#1502]
SBA is running behing a proxy (Spring Cloud Gateway=SCG). In SBA's application.yml I defined this public-url:
```
spring:
  boot:
    admin:
      ui:
        public-url: http://localhost:8080/admin  #SCG is running on locolhost:8080. 
```
To enable security, I added these 2 dependencies:
```
<dependency>
	<groupId>de.codecentric</groupId>
	<artifactId>spring-boot-admin-server-ui</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-security</artifactId>
</dependency>
```
The problem is, when I hit `http://localhost:8080/admin` SBA redirects to `http://localhost:8080/login` instead of `http://localhost:8080/admin/login`. The `${spring.boot.admin.ui.public-url}` property is not used. 
Is it normal?
Thanks
