### ISSUE TITLE
Unable to log in when deployed to Linux

### ISSUE THREAD

**Issue by developers-youcong** [codecentric/spring-boot-admin#1521]
** Question **
SpringBoot Admin Server Unable to log in when deployed to Linux.

** Bug report **
SpringBoot Admin Server Unable to log in when deployed to Linux.

Profile contents:
```
# Spring
spring:
  security:
    user:
      name: test
      password: test1234
  boot:
    admin:
      ui:
        title: Monitor
```
Local verification that the login was successful.
I looked for it for a long time, but I couldn't find the reason.
There are no specific errors reported in the online log.

Enter the correct username and password prompt, as shown in the figure：
![image](https://user-images.githubusercontent.com/45055576/96406359-d7406e00-1211-11eb-9445-d5b9204df47a.png)

** Version**
JDK:1.8
SpringBoot:2.2.6.RELEASE
Admin Server:2.2.3
