### ISSUE TITLE
Need to explicitly define port for https / http protocol

### ISSUE THREAD

**Issue by kibbled** [codecentric/spring-boot-admin#1576]
Example, if I remove the default port (see below) Spring Admin will not recognize the configuration and it will not show up in the list of applications. I think the framework should be smart enough to figure out the default ports for http & https.

```
spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            test:
              - uri: http://instance1.intern:80
```
