### ISSUE TITLE
Issues with reaching Spring Boot Admin (running in Eureka) behind an Nginx reverse proxy

### ISSUE THREAD

**Issue by filpano** [codecentric/spring-boot-admin#1621]
We have the following set-up:

1. Spring Boot Admin (`2.3.1`) running in Eureka under the `/admin` path
2. Keyloak integration which redirects to the Keycloak login page and back upon successful login.
3. An Nginx reverse proxy set up for the Eureka base path, behind basic auth.

The following are the relevant Eureka settings:

```yaml
eureka:
  client:
    register-with-eureka: false
    # Registry must be fetched so that Spring Boot Admin knows that there are registered applications
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.hostname}:${eureka.port}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      # Needed to trigger info and endpoint update after restart
      startup: ${random.int} 
  environment: eureka-server

# Spring Boot Admin relevant settings
spring:
  cloud.inetutils.preferred-networks: 10.0
  main:
    allow-bean-definition-overriding: true
  # Increase max response size for large requests, e.g. /actuator/loggers request.
  codec.max-in-memory-size: 1048576
  boot:
    admin:
      client:
        prefer-ip: true
      # Since we are running in Eureka, "/" is already the context path for Eureka itself.
      # Register SBA under the "/admin" root path.
      context-path: /admin
```

Keycloak integration has been tested to work without the Nginx proxy, so I'll be omitting those details. 

The following is our Nginx configuration:

```text
server {
  listen 443 ssl;
  server_name <eureka_url>;
 
  ssl on;
  ssl_certificate <certificate_file>;
  ssl_certificate_key <key_file>;
 
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Original-URI $request_uri;
 
  client_max_body_size 10000M;
  large_client_header_buffers 4 64k;
 
  location / {
    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/.htpasswd;
    proxy_pass <http://<internal-ip>:<port>
  }
}
```

Without Nginx, the following happens:

1. Navigating to <eureka_url> shows Eureka correctly.
2. Navigating to <eureka_url>/admin correctly redirects to the Keycloak authentication page, and redirects back to the SBA UI upon valid login.

*With* Nginx, the following happens:

Navigating to <eureka_url> returns a `302 Found`, redirecting to the Keycloak authentication page. The request/response headers look as follows (some details omitted):
![image](https://user-images.githubusercontent.com/5376771/106628822-7ba8af00-657a-11eb-89d3-e66354fd4ebc.png)

where seemingly no `X-Forwarded-*` headers are being set.

Similarly, navigating to `/admin` does not work. This seems similar to the following issue: https://github.com/codecentric/spring-boot-admin/issues/1496, and we have tried the potential solutions listed there (including the options mentioned in https://codecentric.github.io/spring-boot-admin/current/#_running_behind_a_front_end_proxy_server), unfortunately to no effect.

Any idea how could we debug this behaviour?
