### ISSUE TITLE
[client] actuator info less when use service-base-url

### ISSUE THREAD

**Issue by Alice52** [codecentric/spring-boot-admin#1739]
## usage in docker about ip

- version: `2.2.4`

1. below is my config, but I got less actuator info, why less info? 

   ```yml
    spring:
    boot:
        admin:
        client:
            url: "http://localhost:8010/"
            instance:
                service-base-url: "http://localhost:8010"
                prefer-ip: true
            metadata:

    management:
    endpoint:
        health:
        show-details: always
    endpoints:
        web:
        exposure:
            include: "*"
    ```    

    ![image](https://user-images.githubusercontent.com/42330329/121214454-b799ab00-c8b1-11eb-9971-215f72404842.png)

2. but if i remove `spring.boot.admin.client.instance.service-base-url`, I got full actuator info, 
  **`but the url is not clearly, so change by [refer to](https://github.com/codecentric/spring-boot-admin/issues/1238)`**

    ![image](https://user-images.githubusercontent.com/42330329/121214929-25de6d80-c8b2-11eb-89b1-e9e3db22b78e.png)

3. Expectation: I want to use `spring.boot.admin.client.instance.service-base-url`, and get full actuator info.
 
@joshiste please help me out this trouble, thanks.
