### ISSUE TITLE
Discrepancies in docs, and failure to refresh instances.

### ISSUE THREAD

**Issue by davidkarlsen** [codecentric/spring-boot-admin#1788]
config states to define `spring.cloud.kubernetes.discovery.service-labels` for filtering, but it seems to actually be `spring.boot.admin.discovery.instances-metadata` [1].

Also, sb-admin seems to only discover instances on boot-up, if I scale a deployment up, it won't list the new instances. My config is:

```
package com.tietoevry.fss.baas;

import de.codecentric.boot.admin.server.config.EnableAdminServer;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableAdminServer
@EnableDiscoveryClient
@EnableScheduling
public class AdminApplication {

  public static void main(String[] args) {
    SpringApplication.run(AdminApplication.class, args);
  }


}
```

[1]
```
application.yaml: |
    spring:
      cloud:
        kubernetes:
          reload:
            enabled: true
          discovery:
            all-namespaces: true
            service-labels:
              spring-boot: "true" <-- no use
      boot:
        admin:
          ui:
            public-url: https://eos-tac-spring-boot-admin-d1.apps.os-global.finods.com
          discovery:
            #services:
            #- "spring-boot*"
            instances-metadata:
              spring-boot: "true" <-- actually need to be set here
```
