### ISSUE TITLE
Why one service has two status, one up and one down?

### ISSUE THREAD

**Issue by JamesTaylor04** [codecentric/spring-boot-admin#1879]
- Question
Spring boot service has started, but in Admin UI Page, the service has two status, one up and one down, how to resolve this?
- Environment
  spring boot: 2.4.2
  spring-boot-admin: 2.4.3
  nacos: 2.0.3
- Exception Picture
![image](https://user-images.githubusercontent.com/46660297/145777545-b886352a-4896-4ec0-b45e-5e5024294706.png)

- My Configuration
![image](https://user-images.githubusercontent.com/46660297/145777669-b15325e4-1b9e-407b-b118-25cca72c70fa.png)

![image](https://user-images.githubusercontent.com/46660297/145777725-36a28b5b-b9c9-4b78-be56-0137f8e8f568.png)

- Pom File
![image](https://user-images.githubusercontent.com/46660297/145777809-27cf9c91-49ee-435c-a97b-3c915adf131c.png)

**Comment by JamesTaylor04** [comment]
I resolve the problem, we have to add metadata for nacos
```yaml
spring:
  cloud:
      nacos:
        discovery:
          metadata:
            management.context-path: /pwps/actuator
```
