### ISSUE TITLE
Client management endpoints secured

### ISSUE THREAD

**Issue by Controlix** [codecentric/spring-boot-admin#198]
I have a very simple spring-boot application that uses spring-security to secure its management endpoints. The configuration in my application.yml file is
```
security:
  ignored: /
  user:
    name: demo
    password: demo
```
When I enter a management endpoint in my browser I get a popup that requests a username/password and after I enter the credentials I get the requested information.

Then I add the spring-boot-admin-client-starter to my project and I configure the spring.boot.admin.url.
After starting it up I can see the application in the admin UI. However when I want to see the details I get a popup asking me for a username/password. But whatever I enter it always fails.
If I cancel the popup I get an error message

> status":401,"error":"Unauthorized","message":"Full authentication is required to access this resource"

I searched the issues related to secrity but could not figure out what I need to do to make this working.

I use spring-boot-admin-client-starter:1.3.3 and spring-boot-admin-sample:1.4.0-SNAPSHOT

**Comment by WillBDaniels** [comment]
looks like this is a bug with 1.3.3, switch over to 1.3.2 and it works fine as expected (credentials get passed properly)

**Comment by nabirkin** [comment]
I have the same situation, but it doesn't work with 1.3.2 also.
My configuration:
- for admin project:
```yaml
server:
  port: 8081
security:
  user:
    name: admin
    password: admin
```
- for client project:
```yaml
server:
  port: 8080
spring:
  boot:
    admin:
      url: http://localhost:8081
      username: admin
      password: admin
security:
  basic:
    enabled: false
  user:
    name: user
    password: user
```

Note: if
