### ISSUE TITLE
spirng-boot-admin-server 显示健康状态401

### ISSUE THREAD

**Issue by niceyou99** [codecentric/spring-boot-admin#2158]
version：
![image](https://user-images.githubusercontent.com/116698268/198956172-212777f9-4f96-4b0a-af28-2a3f5ac0bd7d.png)

yml:
![image](https://user-images.githubusercontent.com/116698268/198956636-bc99e773-6fd9-4253-bc48-bbce22038fb4.png)

这个服务就是 admin-server 服务端自己  注册到了nacos上面  我想问的时候显示401我应该怎么去解决
![image](https://user-images.githubusercontent.com/116698268/198956235-5f868071-c783-4003-9127-dc104c2d0726.png)
![image](https://user-images.githubusercontent.com/116698268/198956340-2660731f-0b5c-49dc-9326-6251118b36e0.png)

**Comment by ulischulte** [comment]
Translated issue text:
The service is admin-server and the server itself is registered to nacos and when I want to ask it shows 401 how should I fix it?

**Comment by ulischulte** [comment]
Hi @niceyou99,

you misconfigured the client discovery a bit. Since you are using nacos as a discovery client, there is no need to configure spring.boot.admin.client.url, username and password. You don't even need a dependency to spring-boot-admin-starter-client.
You need to put this configuration into the discovery configuration within the metadatamap in order to passthrough security relevant information. You will find a sample configuration here: https://github.com/codecentric/spring-boot-admin/blob/85ec2b7f61c60e2435ae645cb2017492ca75c940/spring-boot-admin-samples/spring-boot-admin-sample-eureka/src/main/resources/application.yml#L44

We assume a a configuration might look similar to this:

```
nacos:
  discovery:
    register:
      metadata:
        user.name: "user"         #These two are needed so that the server
        user.password: "password" #can access the protected client endpoints
   ```     

I hope this helps a bit.

Regards,
Uli
