### ISSUE TITLE
spring boot server ui 401 error when logging in

### ISSUE THREAD

**Issue by livk-cloud** [codecentric/spring-boot-admin#2164]
![image](https://user-images.githubusercontent.com/50291874/202607095-3c3975e5-5ee2-4d28-b09c-adb351153297.png)

security config
```java
@Configuration
public class SecurityConfig {

    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http,
                                                   AdminServerProperties adminServer) throws Exception {
        SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
        successHandler.setTargetUrlParameter("redirectTo");
        successHandler.setDefaultTargetUrl(adminServer.path("/"));
        return http.authorizeHttpRequests()
                .requestMatchers(adminServer.path("/assets/**"))
                .permitAll()
                .requestMatchers(adminServer.path("/variables.css"))
                .permitAll()
                .requestMatchers(adminServer.path("/actuator/info"))
                .permitAll()
                .requestMatchers(adminServer.path("/actuator/health"))
                .permitAll()
                .requestMatchers(adminServer.path("/login"))
                .permitAll()
                .anyRequest()
                .authenticated()
                .and()
                .formLogin()
                .loginPage(adminServer.path("/login"))
                .successHandler(successHandler)
                .and()
                .logout()
                .logoutUrl(adminServer.path("/logout"))
                .and()
                .httpBasic(Customizer.withDefaults())
                .csrf()
                .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
                .ignoringRequestMatchers(new AntPathRequestMatcher(adminServer.path("/instances"), HttpMethod.POST.toString()),
                        new AntPathRequestMatcher(adminServer.path("/instances/*"), HttpMethod.DELETE.toString()),
                        new AntPathRequestMatcher(adminServer.path("/actuator/**")))
                .and()
                .rememberMe()
                .key(UUID.randomUUID().toString())
                .tokenValiditySeconds(1209600)
                .and()
                .build();
    }
}
```

```yml
server:
  port: 7777

spring:
  boot:
    admin:
      instance-auth:
        default-user-name: ${spring.security.user.name}
        default-password: ${spring.security.user.password}
  security:
    user:
      name: livk
      password: 123456
      roles: USER

  data:
    redis:
      host: livk.com
      password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'

```

The console doesn't throw any exception

spring boot admin version:3.0.0-M5
spring boot version:3.0.0-RC2
