### ISSUE TITLE
UI not fully functional if running at custom context-path.

### ISSUE THREAD

**Issue by ztomic** [codecentric/spring-boot-admin#2175]
## Spring Boot Admin Server information

- **Version**:
  3.0.0-M7

- **Spring Boot version**:
  3.0.0

- **Configured Security**:
  

- **Webflux or Servlet application**:
  servlet

With new version, if it is running on non-default context-path, e.g.:

```yaml
spring:
  boot:
    admin:
      ui:
        external-views:
          - label: Eureka Dashboard
            url: ${eureka.dashboard.path}
            iframe: true        
      context-path: /spring-boot-admin
```

Page refresh in browser, back button, etc. are not working, external views also are not working.
