### ISSUE TITLE
Admin UI is giving 502 when running in Istio

### ISSUE THREAD

**Issue by mirza-ali-ctct** [codecentric/spring-boot-admin#2222]
## Spring Boot Admin Server information

- **Version**:
  2.7.10

- **Spring Boot version**:
  

- **Configured Security**:

- **Webflux or Servlet application**:

## Client information

- **Spring Boot versions**:
2.7

- **Used discovery mechanism**:
 kubernetes

- **Webflux or Servlet application**:

## Description
We are using Spring Boot Admin UI in Istio and have configured the following settings for SBAC UI:

```yaml
configmap:
  application.yaml: |-
    logging:
      level:
        root: DEBUG
    management:
      scheme: https
    server:
      forward-headers-strategy: NATIVE
    spring:
      cloud:
        kubernetes:
          discovery:
            enabled: true
            all-namespaces: true
            service-labels:
              "[monitoring.ctct.io/sbac]": true
      boot:
        admin:
          # set this to the ingre1ss url and protocol
          ui:
            public-url: <<The URL>>>  
          discovery:
            converter:
              management-context-path: /actuator
```
We are able to see the UI but when it connects to specific pod, the UI returns 502. The app we are trying to connect has a headless service which allows the connection by its IP within Istio. We curled the health/actuator end points from the SBAC pod and got a valid response but the UI is alway getting 502. We see following error in the SBAC pod

```text
boot-admin-console 2023-01-12 19:26:54.480 DEBUG 1 --- [or-http-epoll-3] r.n.http.client.HttpClientOperations    
   : [db6578e5-10, L:/172.30.208.27:34026 - R:172.30.198.29/172.30.198.29:8080] Received response (auto-read:false) : RE 
 SPONSE(decodeResult: success, version: HTTP/1.1)                                                                        
 spring-boot-admin-console HTTP/1.1 200 OK                                                                               
 spring-boot-admin-console x-content-type-options:                                                          
 spring-boot-admin-console x-xss-protection:                                                                
 spring-boot-admin-console cache-control:                                                                   
 spring-boot-admin-console pragma:                                                                          
 spring-boot-admin-console expires:                                                                         
 spring-boot-admin-console x-frame-options:                                                                 
 spring-boot-admin-console content-type:                                                                    
 spring-boot-admin-console date:                                                                            
 spring-boot-admin-console x-envoy-upstream-service-time:                                                   
 spring-boot-admin-console server:                                                                          
 spring-boot-admin-console transfer-encoding:                                                               
 spring-boot-admin-console 2023-01-12 19:26:54.480 DEBUG 1 --- [or-http-epoll-3] r.n.r.DefaultPooledConnectionProvider   
   : [db6578e5-10, L:/172.30.208.27:34026 - R:172.30.198.29/172.30.198.29:8080] onStateChange(GET{uri=/actuator/health,  
 connection=PooledConnection{channel=[id: 0xdb6578e5, L:/172.30.208.27:34026 - R:172.30.198.29/172.30.198.29:8080]}}, [r 
 esponse_received]) 
```
Any suggestions?
