### ISSUE TITLE
Error when rendering external view when 'iframe' property is set to true

### ISSUE THREAD

**Issue by andrew2184** [codecentric/spring-boot-admin#2328]
## Spring Boot Admin Server information

- **Version**: 3.0.1

- **Spring Boot version**: 3.0.3

- **Webflux or Servlet application**: Servlet

## Description

When adding an external view and setting "iframe: true", the view does not render.

```
  boot:
    admin:
      ui:
        external-views:
          - label: "My External View"
            url: "/external-view.html"
            iframe: true
            order: 3
```

The browser's console shows an error of 

![image](https://user-images.githubusercontent.com/3290478/225159270-da328fdc-c471-42de-b666-5d81cb82cc05.png)
