### ISSUE TITLE
how to disable to access admin server webpage?

### ISSUE THREAD

**Issue by linvaux** [codecentric/spring-boot-admin#2523]
Excuse me，how to disable admin web access? I am useing spring-boot-starter-web:2.7.12, spring-boot-admin-starter-server:2.7.4. I had config this in my admin server application.yml:
```yml
server:
  port: 8080
spring:
  boot:
    admin:
      ui:
        enabled: false

  application:
    name: spring-admin-server
management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
```
But I can still access the admin web page,I look forward to your answer
