### ISSUE TITLE
[K8s Discovery] Filtering for custom service labels

### ISSUE THREAD

**Issue by ngc4579** [codecentric/spring-boot-admin#2526]
## Spring Boot Admin Server information

- **Version**: 2.7.10
- **Spring Boot version**: 2.7.10

- **Configured Security**: Keycloak
- **Webflux or Servlet application**: Servlet

## Client information

- **Spring Boot versions**: (various)
- **Used discovery mechanism**: Kubernetes
- **Webflux or Servlet application**: Servlet

## Description

As per documentation I should be able to configure the necessary Service labels for service discovery via application properties:

```
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
        primary-port-name: http-management
        service-labels:
          some.arbitrary.prefix/spring-boot-admin: true
```

However, this does not seem to work. SBA does not pick up services with the mentioned annotation. When configuring an annotation like `spring-boot-admin: true`, discovery works as expected.

Is there any mechanism filtering configured service labels for special characters, not allowing e.g. `/` to appear in a label?

In fact I'm not sure if this is actually a bug or rather a misinterpretation or misconfiguration issue.
