### ISSUE TITLE
Native - UI Breaks on external views. label undefined

### ISSUE THREAD

**Issue by woodstockain** [codecentric/spring-boot-admin#2807]
## Spring Boot Admin Server information

Java17
GraalVM 22.3.3
Spring Cloud 2022.0.3

- **Version**:
3.1.7

- **Spring Boot version**:
3.1.4

- **Webflux or Servlet application**:
Servlet

## Description
** Bug report **

When when running native/binary compiled Spring Boot Admin Server with an external view configured:

Application.yml
```yml
spring:
  boot:
    admin:
      ui:
        external-views:
          - label: 'SmokeTest'
            url: "${smoketest.url}"
```

The UI breaks/fails to load with error:
`Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')`

![image](https://github.com/codecentric/spring-boot-admin/assets/54625704/8a6469e1-b7c2-4159-8ae2-1ec2aa8d5bf8)

![image](https://github.com/codecentric/spring-boot-admin/assets/54625704/05258c3c-cd82-4cba-b01b-fbd986122c38)
