### ISSUE TITLE
White screen when route with traefik

### ISSUE THREAD

**Issue by Jolymmiles** [codecentric/spring-boot-admin#3144]
## Spring Boot Admin Server information

- **Version**:
3.2.1

- **Spring Boot version**:
3.2.2

- **Configured Security**:
  basic auth

- **Webflux or Servlet application**:
How to find?

## Description

I have traefik to route all reqeusts via domain and subdomain names, my java spring server works fine and i can go to swagger page via domain.
Also Spring Boot Admin Server maybe work fine, but problem in white screen when i come into page of spring boot admin server. Its just nothig, also a have ssl, but browser said what page dont have them.

compose.yaml

```
version: '3.8'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8081
    environment:
      - PORT=8081
      - SECURITY_USER=admin
      - SECURITY_PASSWORD=admin
      - TELEGRAM_NOTIFICATION=true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-admin.rule=Host(`admin.example.com`)"
    networks:
      - proxy


networks:
  proxy:
    external: true
```
