### ISSUE TITLE
Instance metadata's management.context-path doesn't get detected by spring boot admin's DiscoveryListener

### ISSUE THREAD

**Issue by sallampalli** [codecentric/spring-boot-admin#324]
So, as per http://codecentric.github.io/spring-boot-admin/1.3.3/#spring-cloud-discovery-support

Since my management context path is different than root since the client app is a war, we have a diff context path , so I tried to set in the meta data map in my client.
```
## Eureka client properties ##
eureka.instance.metadataMap.instanceId=${spring.application.name}:${spring.application.instance_id}
eureka.instance.metadataMap.management.context-path=/sample
eureka.instance.nonSecurePort=8101
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.registerWithEureka: true
eureka.client.fetchRegistry: true
```

My Server config 
```
@SpringBootApplication
@EnableEurekaServer
@EnableAdminServer
@EnableDiscoveryClient
public class PlatformApplication {}
```

Server props
```
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false      

spring.boot.admin.context-path: /admin
spring.boot.admin.hazelcast.enabled: false
```
Spring Cloud Version on the server component : Brixton.SR6
Admin Server Version : 1.3.7

It still doesnt return the managementUrl appended to the management context path from the instance metadata of the client. I checked the api response of admin. Am I missing something ?
And I think thats why it is showing OFFLINE in the admin UI.
