### ISSUE TITLE
Context-Path error in microservice

### ISSUE THREAD

**Issue by marvindaviddiaz** [codecentric/spring-boot-admin#342]
I have the following configuration in my microservice:
```
spring:
  application:
     name: security-view-angular
  boot:
    admin:
      client:
        service-url: http://172.16.5.79:9080/security-view-angular/
        management-url: http://172.16.5.79:9080/security-view-angular/
        health-url: http://172.16.5.79:9080/security-view-angular/health 
     
server:
  port: 9080
  context-path: /security-view-angular
```
But in admin view the micro service appear with status 'DOWN'.  This is the log en console:
`2016-11-21 17:39:23.137  INFO 13132 --- [freshExecutor-0] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=302dcf58, name=SECURITY-VIEW-ANGULAR, managementUrl=http://172.16.5.79:9080, healthUrl=http://172.16.5.79:9080/health, serviceUrl=http://172.16.5.79:9080] registered `

I am using 1.4.3 version.
