### ISSUE TITLE
cannot auto discovery microservice 

### ISSUE THREAD

**Issue by HelloDhero** [codecentric/spring-boot-admin#3914]
env:
spring boot admin: 3.4.1
consul: v1.16.2(one node)

step 1: start spring-boot-admin
step 2: start other microservice

result : Not every time a newly launched service can be discovered

reason: method discoveryClient.getInstances can not read latest data

**Comment by HelloDhero** [comment]
the same may occurred on RouteRefreshListener

**Comment by HelloDhero** [comment]
The following code work ok ! just add sleep
Thread.sleep(Duration.ofSeconds(5));
discoveryClient.getServices().stream()
.filter(serviceId -> !"consul".equalsIgnoreCase(serviceId))
.forEach(id -> discoveryClient.getInstances(id)
        .forEach(serviceInstance -> LOGGER.error(serviceInstance.getInstanceId())));

**Comment by erikpetzold** [comment]
Do you have @EnableScheduling Annotation on your Admin Server? This is required for searching new services.

**Comment by HelloDhero** [comment]
yes, There is no difference

**Comment by HelloDhero** [comment]
the problem is 'discoveryClient.getInstances(id)' cannot read the latest data from consul

**Comment by erikpetzold** [comment]
You need to add some more details to help us understand the context of your messages.

First you wrote, that some code snippet is working. Where is is working? Where did you add this? Where did you execute the code?

Then you added another snippet (that is part of the first one) and say it does not work. This contradicts your first message. Also here: what do you mean with "cannot read"? Is there some network issue? Does cosul not have the data? Is the response not readable? Does Consul not provide the correct data? Do you get some error message in the logs?

In your initial message you said "Not every time", so does it mean it is working somthimes? Maybe you just hav to wait a bit longer or decrease some interval? In what circumstances does it work?

Can you provide some sample project showing your problem?

**Comment by HelloDhero** [comment]
InstanceDiscoveryListener.discover can be call when service register, 
<img width="790" alt="WechatIMG1149" src="https://github.com/user-attachments/assets/dd62e739-7ef0-4ad5-9eb6-1fa3d246b2d3" />

above is the code to register to bootAdmin , line 126 can get the service but line 128 can not get instances

if your add a custom @EventListener to deal HeartbeatEvent like `discover` method and add `sleep` in the method , `getInstances` work ok

**Comment by HelloDhero** [comment]
`Not every time` mean below
step 1、start `A` service , bootAdmin not discovery 
stop 2、start `B` service , bootAdmin can discovery `A` , but B cannot

**Comment by SteKoe** [comment]
I have tried to reproduce the issue, too, without any luck. As soon as the servies appear in consule UI, the state is reflected in Spring Boot Admin. Please check if the services are registered at consul, do they appear in the UI at the registration side? As my colleague said, we need a project to reproduce the issue in order to help you.

**Comment by HelloDhero** [comment]
I'm sure I saw it on Consul UI

**Comment by HelloDhero** [comment]
![dependency-graph](https://github.com/user-attachments/assets/be0adeb7-aee1-4174-b570-da61c0f3ebe9)

**Comment by HelloDhero** [comment]
```
logging.config: ${logging.config}
server.port: 7777
spring:
    profiles.active: ${profilesActive}
    application.name: ${spring.application.name}
    boot.admin:
        discovery.ignored-services: consul
        ui:
            title: 应用列表
            login-icon: assets/img/icon-spring-boot-admin.svg
            brand: <img src="${spring.boot.admin.ui.login-icon}"><span>${spring.boot.admin.ui.title}</span>
            available-languages: en,zh-CN
            view-settings:
                - name: applications
                  enabled: false
                - name: about
                  enabled: false
    security.user:
        name: ${bootAdminUsername}
        password: ${bootAdminPassword}
    cloud.consul:
        host: ${consul.host}
        discovery:
            heartbeat.enabled: true
            metadata:
                user-name: ${bootAdminUsername}
                user-password: ${bootAdminPassword}
            prefer-ip-address: ${preferIpAddress}
            query-passing: true
management:
    endpoints.web.exposure.include: '*'
    endpoint.health.show-details: always
    endpoint.env.show-values: always
    endpoint.configprops.show-values: always
    prometheus.metrics.export.pushgateway:
        enabled: false
        push-rate: 10s
        shutdown-operation: post
        job: ${spring.profiles.active}_${spring.application.name}
        grouping-key:
            instance: ${spring.cloud.client.ip-address}:${server.port}

```
