### ISSUE TITLE
spring.boot.admin.monitor.status-interval must be greater than 1s, which is not documented.

### ISSUE THREAD

**Issue by JohanNordlinder** [codecentric/spring-boot-admin#4142]
When running with the following configuration:
```
spring:
  boot:
    admin:
      monitor:
        default-timeout: 1s
        status-interval: 1s
```

All registered applications stay in OFFLINE mode due to the error:
```
details={exception=java.util.concurrent.TimeoutException, message=Did not observe any item or terminal signal within 0ms in 'log' (and no fallback has been configured)}
```

I think the reason 1s becomes 0ms is here: https://github.com/codecentric/spring-boot-admin/blob/0eabdd155a8a638d652988ce50dbefc61b994ce2/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/StatusUpdater.java#L96

This basically means that the minimum value is `status-interval: 1001ms`. 

It would be good for this to be documented so that others don't run into the same problem as me.
