### ISSUE TITLE
org.springframework.web.util.NestedServletException:Request processing failed; nested exception is java.lang.IllegalStateException: Can't set AsyncWebRequest with concurrent handling in progress

### ISSUE THREAD

**Issue by coder-han** [codecentric/spring-boot-admin#421]
### Error
```
org.springframework.web.util.NestedServletException:Request processing failed; nested exception is java.lang.IllegalStateException: Can't set AsyncWebRequest with concurrent handling in progress
```
### application.yml

```
spring:
  application:
    name: benyue-monitor
  cloud:
    config:
      enabled: false
server:
  port: 18001


eureka:
  client:
    service-url:
      defaultZone: http://eureka1:11001/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    ip-address: ${service_ip:127.0.0.1}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10

```

This error has been
