### ISSUE TITLE
Didn't have good url for heath in https MicroService

### ISSUE THREAD

**Issue by bokc** [codecentric/spring-boot-admin#425]
I have a microService with this Eureka configuration:
```
eureka:
    client:
        enable: true
        registerWithEureka: true
        fetchRegistry: true
        registryFetchIntervalSeconds: 5
        securePortEnabled: true
        serviceUrl:
            defaultZone: https://fr-dev.fdi-logbox.com:8761/eureka/
        healthcheck:
            enabled: true
    instance:
        hostname: fr-kuntz.fdi-logbox.com
        leaseRenewalIntervalInSeconds: 10
        statusPageUrl: https://${eureka.instance.hostname}:${management.port}/${management.context-path}/info
        healthCheckUrl: https://${eureka.instance.hostname}:${management.port}/${management.context-path}/health
        homePageUrl: https://${eureka.instance.hostname}:${server.port}/
        securePort: ${management.port}
        securePortEnabled: true
        nonSecurePortEnabled: false
        metadata-map:
            management.context-path: ${management.context-path}
            management.port: ${management.port}
            health.path: /${management.context-path}/health
```

SBA get information of this MS but not the Health. On the header of the UI, the "management URL" is good but the "Health URL" was wrong.

If il remove the  securePortEnabled and nonSecurePortEnabled from my configuration, I got good health but management URL was wrong (http not https).
