### ISSUE TITLE
Children of external views don't render when iframe is set to true

### ISSUE THREAD

**Issue by hanpov** [codecentric/spring-boot-admin#4259]
## Spring Boot Admin Server information

- **Version**: 3.4.3
  

- **Spring Boot version**:  3.4.3
  

- **Configured Security**: basic auth
  

- **Webflux or Servlet application**: Servlet
  

## Client information

- **Spring Boot versions**: 3.4.4
  

- **Used discovery mechanism**: consul
  

- **Webflux or Servlet application**: Servlet
  

## Description

The property `iframe` does not work for `children` of `external-views`. Essentially, taking an example from the samples, doing this doesn't work:

```
spring:
  boot:
    admin:
      ui:
        external-views:
          - label: Link w/o children
            children:
              - label: "📖 Docs"
                url: https://codecentric.github.io/spring-boot-admin/current/
                iframe: true
              - label: "📦 Maven"
                url: https://search.maven.org/search?q=g:de.codecentric%20AND%20a:spring-boot-admin-starter-server
                iframe: true
``` 
Vue.js throws an error about not finding a route to build the list of children for the dropdown.
