### ISSUE TITLE
Long health request + Read Timeout

### ISSUE THREAD

**Issue by schmidp** [codecentric/spring-boot-admin#494]
I'm monitoring a spring application.
This spring application has a health check for an upstream service.
The http connection to this upstream service times out after 10 seconds.

```
curl -u XXXX:XXXX http://localhost:5100/actuator/health
{
  "status" : "DOWN",
  "tshHealthCheck" : {
    "status" : "DOWN",
    "Result" : "Exception while contacting TSH: connect timed out"
  },
  "vcfgHealthCheck" : {
    "status" : "UP"
  },
  "diskSpace" : {
    "status" : "UP",
    "total" : 8318783488,
    "free" : 6204555264,
    "threshold" : 10485760
  },
  "db" : {
    "status" : "UP",
    "database" : "MySQL",
    "hello" : 1
  }
}
real	0m10.109s
user	0m0.000s
sys	0m0.004s
```

And the actuator health endpoint of the spring application reports the correct status.

But in spring boot admin I see this under the application overview: 

<img width="482" alt="screen shot 2017-07-12 at 09 28 28" src="https://user-images.githubusercontent.com/10045/28106562-90b7b6cc-66e4-11e7-8904-b7eeb16f9568.png">

This is my spring boot admin config:

```
spring:
  application:
    name: "spring-admin"
  boot:
    admin:
      url: https://XXXXX:5000
      monitor:
        connect-timeout: 5000
        read-timeout: 30000
```

Before I increased the connection and read-timeout, spring boot was reporting the application as offline instead of down. So the timeouts seem to have some effect.

What I'm expecting is something like this, with the TSH service down:

<img width="474" alt="screen shot 2017-07-12 at 09 30 30" src="https://user-images.githubusercontent.com/10045/28106609-c87256da-66e4-11e7-8adc-711dcf7a5a4f.png">
