### ISSUE TITLE
Simplify using SimpleDiscoveryClient

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-admin#505]
Since SBA contains the `SimpleDiscoverClient` anyway (since it depends on `spring-cloud-commons` due to zuul). It would be useful that adding a `SimpleDiscoveryClient` configuration should work out of the box. 

Sample config
```yml
spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            test:
              - uri: http://example.com
                metadata:
                  label: static
                  management.context-path: /actuator
```

The only thing todo is, making the `ApplicationDiscoveryListener` listen for the `ApplicationReadyEvent`, since no `InstanceRegistered` or `HeartbeatEvent` is fired.
