### ISSUE TITLE
Emails notifications are not working 

### ISSUE THREAD

**Issue by manjunadh** [codecentric/spring-boot-admin#507]
Hi ,
Email notifications are not working for me .

 have the following dependencies in gradle :+1: 

compile("de.codecentric:spring-boot-admin-server:${SpringAdminVersion}")
compile("de.codecentric:spring-boot-admin-server-ui-turbine:${SpringAdminVersion}")
compile("de.codecentric:spring-boot-admin-server-ui-hystrix:${SpringAdminVersion}")
compile group: 'org.springframework.boot', name: 'spring-boot-starter-security', version: '1.5.2.RELEASE'
compile("de.codecentric:spring-boot-admin-starter-client:${SpringAdminVersion}")
compile group: 'com.hazelcast', name: 'hazelcast', version: '3.8.2'
	 testCompile group: 'org.springframework.boot', name: 'spring-boot-starter-test', version: '1.5.2.RELEASE'
compile("de.codecentric:spring-boot-admin-server-ui-login:${SpringAdminVersion}")
compile group: 'org.springframework.boot', name: 'spring-boot-starter-mail', version: '1.5.4.RELEASE'

Below are the properties in application.yml:

```
spring:
  application:
    name: spring-boot-admin
  boot:
    admin:
      auto-deregistration: true
      notify:
        mail:
          enabled: true
          from: *******@gmail.com
          to: *******@gmail.com
          host: smtp.gmail.com
          port: 587
          username: *******@gmail.com
          password: *********
          properties:
            mail:
              stmp:
                ssl:
                  enable: true



spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.connectiontimeout: 5000
spring.mail.properties.mail.smtp.timeout: 3000
spring.mail.properties.mail.smtp.writetimeout: 5000
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
```

Please suggest me i am wrong

**Comment by joshiste** [comment]
The  `MailNotifier` only has the properties `to`,`cc`,`from`,`text`,`subject` all other properties are not present. So I guess gmail doesn't accepts your mail because of missing credentials.

**Comment by qcastel** [comment]
ending troubleshooting my gmail setup as well and notice that you did a typo:

```
properties:
            mail:
              **smtp**:
                ssl:
                  enable: true
```
