### ISSUE TITLE
How to configure Turbine url?

### ISSUE THREAD

**Issue by tjuchniewicz** [codecentric/spring-boot-admin#549]
I'm using SBA 1.5.4. My Hystrix dashboard is empty. It shows only "Loading ...".
In browser console I see connection to: `http://localhost/spring-boot-admin/api/turbine/stream?cluster=default` but valid URL for my Turbine is `http://localhost/turbine.stream?cluster=default`. Any way to reconfigure SBA?

**Comment by joshiste** [comment]
Did you see https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui-turbine/src/main/java/spring/boot/admin/turbine/config/TurbineProperties.java ?

**Comment by tjuchniewicz** [comment]
Yes i saw that properties. I'm using following configuration:
```
spring:
  boot:
    admin:
      turbine:
        clusters: default
        location: admin-server
```
and looks like SBA tries to use this url: `http://localhost/spring-boot-admin/api/turbine/stream?cluster=default`. But valid url for me is `http://localhost/turbine.stream?cluster=default`.
