### ISSUE TITLE
Eureka discovery monitoring not working, when instance name is not equals with app name

### ISSUE THREAD

**Issue by szabolcsgnr** [codecentric/spring-boot-admin#552]
`de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener#discover` calls `org.springframework.cloud.client.discovery.DiscoveryClient#getInstances` with the retrieved Application IDs.

When you are using eureka for service registration you can supply an instance ID like that:
```yaml
eureka:
  instance:
    appName: app-name
```

If are using the configuration bootstrap first approach of spring cloud you should supply an app name as well.
```yaml
spring:
  application:
    name: other-app-name-same-app
```

Unfortunatly, eureka discovery client tries to return the instances by the vip address, which in this case will be other-app-name-same-app. As the method invoked with app-name, it will return an empty list, causing these services won`t be registered in the admin application.

In my opinion, it is contract violation in eureka client implementation. Has someone other came across with that issue? I would be open to any suggestions.
