### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by mohita123** [codecentric/spring-boot-admin#572]
Hi,
I have a simple spring boot application running on different profiles with spring security auth.
I included spring admin configuration and it works fine for one profile but not on other.
In the browser for working profile the url hit is http://spring-admin/api/applications/59d73f49/metrics
but for the other profile https://myService/api/manage/metrics is hit and 401 error is thrown.

```
spring:
  boot:
    admin:
      client:
        name: service
        enabled: true
        management-url: http://myService/api/manage
        metadata:
          user:
            name: service
            password: demo
      url: http://spring-admin
      username: name
      password: password


management:
  security:
    enabled: false
  context-path: /manage-api-gateway
  port: 8080

endpoints:
  shutdown:
    enabled: true

zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 600000
  ignoredServices: '*'
  sensitiveHeaders:
  routes:
    ser1:
      path: /manage-ser1/**
      url: http://localhost:8081/manage-ser1/
   ser2:
      path: /manage-ser2/**
      url: http://localhost:8082/manage-file-processor/
...
...
```

same code is there for other profiles.

I have configured security as follow

```
@Configuration
@Order(1)
@EnableWebSecurity
@Profile("!default")
public class AspAdminSecurityConfig extends WebSecurityConfigurerAdapter {

    @Value("${spring.boot.admin.client.metadata.user.name}")
    private String username;

    @Value("${spring.boot.admin.client.metadata.user.password}")
    private String password;

    private String roles = "ADMIN";

    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth.inMemoryAuthentication().withUser(username).password(password).roles(roles);
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .antMatcher("/manage/**").authorizeRequests().anyRequest().hasRole("ADMIN")
                .antMatchers("/manage-ser1/**").permitAll()
                .antMatchers("/manage-ser2/**").permitAll()
                .antMatchers("/manage-ser3/**").permitAll()
                .antMatchers("/manage-ser4/**").permitAll()
                .antMatchers("/manage-ser5/**").permitAll()
                .antMatchers("/manage-ser6/**").permitAll().and()
                .httpBasic().and()
                .csrf().disable();
    }
}
```

what would be the issue for authentication failure?
When I hit the metrics url it works fine for https://myService/api/manage/metrics/
