### ISSUE TITLE
Clients do not always deregister on shutdown/termination

### ISSUE THREAD

**Issue by ctoestreich** [codecentric/spring-boot-admin#576]
We are using OSEv3 and have applications that auto deploy on build, but when stopping the previous applications it would appear that the clients aren't always doing the auto unregistration which leaves stale items in the list.  We are unclear if this is an issue with the way OpenShift stops the applications or a bug with the spring context shutdown.  These are in containers so the PaaS might just be doing a hard terminate on the container process.  If so, perhaps it would be useful to have a purge job running in the admin that could be set to sweep dead apps after X hours for example.

All our apps using the client share a common config like the following

``` yml
spring.boot.admin.url: ${SPRING_BOOT_ADMIN_URL:http://localhost:8888}
spring.boot.admin.period: ${SPRING_BOOT_ADMIN_PERIOD:30000}
spring.boot.admin.client.prefer-ip: ${SPRING_BOOT_ADMIN_CLIENT_PREFER_ID:true}
spring.boot.admin.auto-deregistration: ${SPRING_BOOT_ADMIN_CLIENT_DEREGISTRATION:true}
```

<img width="724" alt="screen shot 2017-10-28 at 11 48 05 am" src="https://user-images.githubusercontent.com/691357/32136614-5ad84bd8-bbd6-11e7-83c6-fed6667db2b1.png">
<img width="1430" alt="screen shot 2017-10-28 at 11 46 41 am" src="https://user-images.githubusercontent.com/691357/32136615-5aeacb0a-bbd6-11e7-9c5c-82572b2f6659.png">
