### ISSUE TITLE
spring boot admin  Additional security authentication information

### ISSUE THREAD

**Issue by xiezhaofeng** [codecentric/spring-boot-admin#583]
My `sping admin client` considering safety reasons, I need this configuration.
```
management:
  security:
#    enabled: false
    roles: ADMIN
security:
  user:
     name: admin
     password: secret

```
In the `spring admin server` how to request attached authentication information?

i need you help.
