### ISSUE TITLE
Question : purpose of spring.boot.admin.client.metadata

### ISSUE THREAD

**Issue by jmichelgarcia** [codecentric/spring-boot-admin#610]
Hi, 

Here's my setup : 

- Eureka server without user/pass configured acessible at localhost:8761
- 1 regular Spring Boot app PREF-SERVICE : 
    - registering to Eureka (Eureka is seing PREF-SERVICE as *UP*)
    - spring boot actuator endpoint secured with userA / passA

My SBA yml below : 
````yml
spring:
  boot:
    admin:
      client:
        metadata:
          user.name: "userA"          #These two are needed so that the server
          user.password:  "passA" #can access the proteceted client endpoints
`````

the logs of SBA states : status=401, **error=Unauthorized, message=Full authentication is required to access this resource**, path=/admin/health}

``
08:17.421 DEBUG 19988578 --- [    updateTask1] d.c.b.a.w.client.ApplicationOperations   : Fetching 'http://localhost:8484/admin/health' for Application [id=5a7e1de1, name=PREF-SERVICE, managementUrl=http://localhost:8484/, healthUrl=http://localhost:8484//admin/health, serviceUrl=http://localhost:8484/]
2017-12-16 01:08:17.474 DEBUG 19988578 --- [    updateTask1] d.c.b.a.w.client.ApplicationOperations   : 'http://localhost:8484/admin/health' responded with <401 Unauthorized,{timestamp=1513382897466, status=401, error=Unauthorized, message=Full authentication is required to access this resource, path=/admin/health},{X-Content-Type-Options=[nosniff], X-XSS-Protection=[1; mode=block], Cache-Control=[no-cache, no-store, max-age=0, must-revalidate], Pragma=[no-cache], Expires=[0], X-Frame-Options=[DENY], WWW-Authenticate=[Basic realm="Administration"], Content-Type=[application/json;charset=UTF-8], Transfer-Encoding=[chunked], Date=[Sat, 16 Dec 2017 00:08:17 GMT]}>
``

**Am I misunderstanding the meaning and usage of** `spring.boot.admin.client.metadata` ?
[Source](http://codecentric.github.io/spring-boot-admin/1.5.5/#_securing_client_actuator_endpoints)

Your help is appreciated.
JMG

**Comment by viruscamp** [comment]
spring.boot.admin.client.metadata is not for spring-boot-admin micro-service, is for the micro-service spring-boot-admin managed. 
And your managed micro-service should depends spring-boot-admin-client. 

In your case: 
spring-boot-admin-client is no need
Your spring-boot-admin micro-service should registered to eureka as an eureka client. 
Your managed micro-service (PREF-SERVICE) 's application.yml:
```yml
eureka.instance.metadata-map:
  user.name: userA
  user.password: passA
```
