### ISSUE TITLE
Is Oauth2 JWT supported?

### ISSUE THREAD

**Issue by HJK181** [codecentric/spring-boot-admin#631]
Hi,

I have an Spring Oauth2 + JWT Setup and I'm trying to setup Spring-Boot-Admin. In die Admin-UI I can see a list of application obtained from Eureka. Unfortunately when hitting the Details button a basic auth popup is presented. I configured the spring-boot-admin application to use oauth2 like so:

```
 security:
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token
      userAuthorizationUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/authorize
      clientId: xxx
      clientSecret: xxx
    resource:
      jwt:
        keyValue: |....|

zuul:
  sensitiveHeaders:
```

Is the combination of Oauth2 + JWT supported by spring-boot-admin?

**Comment by HJK181** [comment]
Solved by setting
```
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3
```
