### ISSUE TITLE
admin server fetch application info failed in docker service because of port problem

### ISSUE THREAD

**Issue by lishengsam** [codecentric/spring-boot-admin#635]
The problem is spring boot admin server show the service as OFFLINE OR DOWN.
My situation is as follows:
I have a service A have registered to eureka server and this service run in docker.Because one service call another service can't with docker inner IP and port, so when we start running a docker service, we attain the public ip as MS_POST variable and public port as MS_PORT variable and bind with the docker service inner ip and 8080 port exposed by docker.
BTW, admin server also have registered to same eureka server.

I have try setting different config to resolve this problem, but none work.  My application.yaml is as follows: 

1. service A run in docker config as follows:

```
spring:
  application:
    name: A
server:
  port: 8080
eureka:
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: xxx.com
    eurekaServerURLContext: eureka
    eureka-server-port: 8761
  instance:
    hostname: ${MS_HOST}
    non-secure-port: ${MS_PORT}
    metadataMap:
      management.port: ${MS_PORT}
management:
  security:
    enabled: false

```
Using this config, spring boot admin server show the A application is OFFLINE in spring boot admin server. Because admin server try the access A service use 8080 port not ${MS_PORT}

2. I try to resolve above problem through changing the config  as follows:
```
spring:
  application:
    name: A

server:
  port: 8080

eureka:
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: xxx.com
    eurekaServerURLContext: eureka
    eureka-server-port: 8761
  instance:
    hostname: ${MS_HOST}
    non-secure-port: ${MS_PORT}

management:
  port:  ${MS_PORT}
  security:
    enabled: false

```
It can't work again but show different error in admin server, which is that A service's status is DOWN because call A service fetch the infomation use  ${MS_PORT}, but this request will redirect to the 8080 port and 404 error show in admin server tab of JOURNAL.

someone know this problem and how to resolve it ?
