### ISSUE TITLE
JMX endpoint is not visible in 2.x

### ISSUE THREAD

**Issue by n0mer** [codecentric/spring-boot-admin#649]
hello, i've included `jolokia-core` dependency (as per https://docs.spring.io/spring-boot/docs/2.0.0.RC1/reference/html/production-ready-jmx.html) - but unable to see 'JMX' tab in spring-boot-admin ui

Using eureka to fetch endpionts, with customization 

```yaml
  boot.admin:
    discovery:
      converter:
        management-context-path: "${management.server.servlet.context-path}/actuator"
```

`jolokia` endpoint is not present in client's `/management/actuator` , although it can be directly opened by navigating to `/management/actuator/jolokia` - so i suppose this is related to https://github.com/spring-projects/spring-boot/issues/11902

Versions used:

```
        springbootVersion = '2.0.0.RC1'
        springCloudVersion = 'Finchley.M6'
        springCloudNetflixVersion = '2.0.0.M6'
        springbootAdminVersion = '2.0.0-SNAPSHOT'
        springIoPlatformVersion = 'Cairo-BUILD-SNAPSHOT'
```

`spring-boot` version is pinned to `2.0.0.RC1`:

```groovy
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group  == 'org.springframework.boot') {
            details.useVersion springbootVersion
        }
    }
}
```
