### ISSUE TITLE
SBA whether application stop send notify or not

### ISSUE THREAD

**Issue by GuoxinL** [codecentric/spring-boot-admin#671]
Hi, I use SBA, if an application stops, SBA will not send notifications, the application will be removed from the server list, The goal I want to achieve is to send notifications after the application has stopped, whether can it can be done.

**Comment by GuoxinL** [comment]
Achieve the purpose of application monitoring.

**Comment by joshiste** [comment]
If you use the spring boot admin client you just need to disable the auto-derigister property.

**Comment by GuoxinL** [comment]
What are the consequences of not having automatic registration?

**Comment by joshiste** [comment]
it will not be deregistered in the application list and shown as offline, this offline state triggers a notification.

**Comment by GuoxinL** [comment]
Do I need to add to all spring-cloud-eureka clients @EnableDiscoveryClient(autoRegister = false)
Is that correct?

**Comment by joshiste** [comment]
you shouldn't mix eureka with sba client. In case you are using eureka you could extend `ApplicationDiscoveryListener` and remove the part where the stale applications get removed.

**Comment by joshiste** [comment]
> Do I need to add to all spring-cloud-eureka clients @enablediscoveryclient(autoRegister = false)
Is that correct?

no. that's something different

**Comment by GuoxinL** [comment]
Thank you very much for your help, but I still don't understand some places.
This is my existing service architecture.
![image](https://user-images.githubusercontent.com/19989609/37390245-47297548-27a2-11e8-82b4-c4d88a34fbab.png)

AdminApplication.java
```java
@Configuration
@EnableAutoConfiguration(exclude = {DataSourceAutoConfiguration.class})
@EnableDiscoveryClient
@EnableAdminServer
@EnableFeignClients(basePackages = "com.xxx.client")
public class AdminApplication {

    public static void main(String[] args) {
        SpringApplication.run(AdminApplication.class, args);
    }

}
```

appplication.yml
```
spring.profiles.active: test

management.security.enabled: false

spring.application.name: @project.artifactId@

spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,activiti

security.user:
    name: xxxx
    password: xxxx

server:
    port: 7080
spring:
  boot:
    admin:
      notify:
        slack:
          enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
eureka.instance:
  preferIpAddress: true
  instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}

```
application-test.yml
```
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@registry-master:8761/eureka/,http://${security.user.name}:${security.user.password}@registry-master:8762/eureka/
```
pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.9.RELEASE</version>
        <relativePath />
    </parent>

    <groupId>com.xxx.admin</groupId>
    <artifactId>xxx-admin</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>

        <!-- no test -->
        <maven.test.skip>true</maven.test.skip>

        <guava.version>19.0</guava.version>

        <spring-cloud.version>Edgware.RELEASE</spring-cloud.version>

        <maven.assembly.plugin.version>3.0.0</maven.assembly.plugin.version>
        <spring.boot.admin.version>1.5.7</spring.boot.admin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xxx.client</groupId>
            <artifactId>xxx-client-message</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-server</artifactId>
            <version>${spring.boot.admin.version}</version>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-server-ui-activiti</artifactId>
            <version>${spring.boot.admin.version}</version>
        </dependency>
        <!--<dependency>-->
            <!--<groupId>de.codecentric</groupId>-->
            <!--<artifactId>spring-boot-admin-server-ui-hystrix</artifactId>-->
            <!--<version>${spring.boot.admin.version}</version>-->
        <!--</dependency>-->
        <!--<dependency>-->
            <!--<groupId>de.codecentric</groupId>-->
            <!--<artifactId>spring-boot-admin-server-ui-turbine</artifactId>-->
            <!--<version>${spring.boot.admin.version}</version>-->
        <!--</dependency>-->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xxx.common</groupId>
            <artifactId>xxx-common-utilities</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <!-- guava -->
        <!--<dependency>-->
            <!--<groupId>com.google.guava</groupId>-->
            <!--<artifactId>guava</artifactId>-->
            <!--<version>${guava.version}</version>-->
        <!--</dependency>-->
        <!-- lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```
