### ISSUE TITLE
Cloud Foundry- Spring boot client showing OFFLINE

### ISSUE THREAD

**Issue by sruthi-kotla** [codecentric/spring-boot-admin#674]
Hi 

Iam facing the below issue. once I push my application to pcf(cloud foundry) I do see that the client application is showing OFFLINE. I tried the above option of adding configration properties in clients .yml file but didnt work out.

I am not using Eureka. its just Spring boot admin and client project

```
spring:
  application:
    name: Sample
  boot:
    admin:
      url: https://admin-project.cfapps.io
      username: user
      password: user
      client:
        management-url: https://sample-hilarious-bonobo.cfapps.io
        health-url: https://sample-hilarious-bonobo.cfapps.io/health
        service-url: https://sample-hilarious-bonobo.cfapps.io        
        prefer-ip: true
management:
  security:
    enabled: false
```

This is my client configuration properties.
This is working fine in my local when I run them in two different ports, but facing issue while testing in cloud foundry.
I tried with VCAP service of admin and binding it to the clien and didnt work out.
Can someone help me out with this?
Thanks in advance..

![image](https://user-images.githubusercontent.com/37380174/37426550-d17178dc-27ec-11e8-8d9e-6d0d2d2e31c6.png)
