### ISSUE TITLE
spring boot admin 2.x bug

### ISSUE THREAD

**Issue by Himly1** [codecentric/spring-boot-admin#700]
Hi,I got some bugs,When i use spring boot admin 2.0.0.SNAPSHOT version to my project

Client config is 
```
server:
  port: 8080

spring:
  boot:
    admin:
      client:
        url: "http://localhost:8081"
        enabled: true
          

management:
  endpoints:
    web:
      exposure:
        include: "*"
```

Server config is

`server.port=8081`

When start the client and server everything is fine.but when i check the client details 、enviroment、loggers... I got error message like this "Fetching environment failed.
Request failed with status code 500"  and  check the server throws exception like this "NoSuchMethodError 
org.springframework.web.reactive.function.client.ClientResponse.create(Lorg/springframework/http/HttpStatus;)" 

![s1](https://user-images.githubusercontent.com/25456846/38595567-2eb8e55a-3d7f-11e8-96f2-588e6bd424b0.png)

![s2](https://user-images.githubusercontent.com/25456846/38595570-348177e0-3d7f-11e8-8a39-7dfa1388f40b.png)

![s3](https://user-images.githubusercontent.com/25456846/38595573-386d338a-3d7f-11e8-932a-1575f6cca055.png)
