### ISSUE TITLE
Spring Boot Admin - client 2.0.0 and server 1.5.7

### ISSUE THREAD

**Issue by matskr90dev** [codecentric/spring-boot-admin#711]
Hi, Is it possible to configure spring boot admin client 2.0.0:SNAPSHOT to works with old 1.5.x admin server?

My application.yml:
```
spring:
  boot:
    admin:
      client:
        url: http://myserver.com/admin/
        api-path: 'api/applications'
        instance:
          name: MyApp
          service-url: http://myserver.com/MyApp/
          service-base-url: http://myserver.com/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
```

My app is successfully register in admin server but I see below errors:

![1](https://user-images.githubusercontent.com/8293063/39082119-580ad28e-454e-11e8-9f3e-bc65d4c9e916.png)

![2](https://user-images.githubusercontent.com/8293063/39082123-609d7474-454e-11e8-823f-dde1bcd2ff26.png)

![3](https://user-images.githubusercontent.com/8293063/39082128-6abd1bc6-454e-11e8-8300-19bffb36b077.PNG)

How can I fix it? Is there a solution other than admin server upgrade? Thanks in advance :)
