### ISSUE TITLE
Unable to customise mail subject

### ISSUE THREAD

**Issue by Sarvesh-D** [codecentric/spring-boot-admin#784]
Hi, i am using SBA 2.0, and when i am setting property
 `spring.boot.admin.notify.mail.subject: testing custom subject`, it is not working and sending mail with default subject "#{application.name} (#{application.id}) is #{to.status}". Going through the `de.codecentric.boot.admin.server.config.AdminServerNotifierAutoConfiguration.MailNotifierConfiguration` i found that, `mailNotifier` bean returns an instance of `de.codecentric.boot.admin.server.notify.MailNotifier` which does not has subject property. I think the bean should return `de.codecentric.boot.admin.notify.MailNotifier` which does has the subject property.

**Comment by joshiste** [comment]
The customization for the mails has been changed. This property doesn't exist anymore. Please consult http://codecentric.github.io/spring-boot-admin/current/#mail-notifications

**Comment by Sarvesh-D** [comment]
I saw the documentation, so does that mean we can't customize the subject?

**Comment by Sarvesh-D** [comment]
I haven't looked at the template, but can it dynamically append spring profile to subject. We have multiple spring profiles for different environment. It would be good to see on which env a a particular app goes down.

**Comment by joshiste** [comment]
add a template similar like this 
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/test/resources/de/codecentric/boot/admin/server/notify/custom-mail.html
to your classpath and set the `spring.boot.admin.notify.mail.template` to that location.
You can use `spring.boot.admin.notify.mail.additional-properties.*` to inject additional properties into the template (like the stage/environment)

**Comment by joshiste** [comment]
The HttpHeadersProvider is used to reach the other applications. If you get a 401 on the `/applications` I guess you've some error in your spring security config of spring boot admin.

**Comment by manish436** [comment]
Hi @joshiste I am trying to implement the same(custom mail template).
here is my yml file:
```
spring:
  application:
    name: springbootadmin
  profiles:
    active: dev
  mail:
    host: prdrelay.host.com
  boot:
    admin:
      notify:
        mail:
          additional-properties:  environment:${spring.profiles.active}
          enabled: true
          from: abx@example.com
          to: xyz@example.com
          ignore-changes: UNKNOWN:UP,OFFLINE:UP
```
and Template file location is also correct with below modification: 
> resources/META-INF/spring-boot-admin-server/mail/status-changed.html 

**from**: ```[[${instance.registration.name}]] ([[(${instance.id})]]) is [[${event.statusInfo.status}]]```
**to**:  ``` [[${instance.registration.name}]] Environment:[[${environment}]] ([[(${instance.id})]]) is [[${event.statusInfo.status}]]```

But it is giving below error:
```
Failed to bind properties under 'spring.boot.admin.notify.mail.additional-properties' to java.util.Map<java.lang.String, java.lang.Object>:
Reason: No converter found capable of converting from type [java.lang.String] to type [java.util.Map<java.lang.String, java.lang.Object>]
```
Please help!
