### ISSUE TITLE
monitor Spring Boot 1.5.x applications with Spring Boot Admin 2.x  via eureka server

### ISSUE THREAD

**Issue by zurhan** [codecentric/spring-boot-admin#838]
I want to monitor Spring Boot 1.5.x applications with Spring Boot Admin 2.x  via eureka server，What should I do?

**Comment by joshiste** [comment]
If the eureka version from Spring Cloud Finchley and Edgware are compatible it should just work

**Comment by zurhan** [comment]
Yeah, I add "management.context-path=/actuator" and it works, but the SBA could not show the METRICS:
Metrics are not supported for Spring Boot 1.x applications.
![image](https://user-images.githubusercontent.com/26533310/43055351-cd3b2df2-8e68-11e8-80af-3cda4696963d.png)

**Comment by joshiste** [comment]
yes and it will ever stay this way for 1.5.x applications. The metrics endpoint has changed so much with 2.x so I decided to support only the new format.

**Comment by SoftwareKing** [comment]
### why 1.5.x applications is work ok，only health found the data ,other endpoint no data？

1.5.x applications no import spring boot admin client，yml config is

```
server:
  port: 8085
# spring.application.name 用于指定注册到Eureka Server上的应用名称
spring:
  application:
    name: spring-cloud-admin-1.5.x
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost/eureka/
 #eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
 #如果不配置,会将当前服务提供者所在的主机名注册到Eureka Server上。
  instance:
    prefer-ip-address: true

management.security.enabled: false

```
but，http://localhost:8081/instances/741e73238eee/actuator/info  result 404

http://localhost:8081/instances/741e73238eee/actuator/env result 404

> Eureka Server is Finchley
