### ISSUE TITLE
with ServerHttpSecurity config，can not show more entpoints

### ISSUE THREAD

**Issue by AaronChen2012** [codecentric/spring-boot-admin#898]
application.yml like this
```
eureka:
  instance:
    metadata-map:
      username: ${SECURITY_USERNAME:admin}
      password: ${SECURITY_PASSWORD:admin}
```

SecurityConfig code:
```
	@Bean
	public MapReactiveUserDetailsService userDetailsService() {
		UserDetails admin = User.withUsername("admin").password("admin").roles("ADMIN").build();
		return new MapReactiveUserDetailsService(admin);
	}
	@Bean
	SecurityWebFilterChain springWebFilterChain(ServerHttpSecurity http) throws Exception {
http.httpBasic();
		http.formLogin();
		http.csrf().disable();
		http.logout().disable();
		
		http.authorizeExchange()
				.matchers(EndpointRequest.to(InfoEndpoint.class, HealthEndpoint.class)).permitAll()
				.matchers(EndpointRequest.toAnyEndpoint()).hasRole(ADMIN_ROLE)//.authenticated()
				.pathMatchers(getActuateEndpoint()).hasRole(ADMIN_ROLE)
				.pathMatchers("/api/**").permitAll()
				.anyExchange().authenticated();
		http.headers().cache().disable();
		return http.build();
}
```
then in admin-ui,only show info tabs,i need show other endpoints
