### ISSUE TITLE
[Questions]How to define different health url for different client?

### ISSUE THREAD

**Issue by biwugang** [codecentric/spring-boot-admin#949]
Use consul as the Spring Cloud Discovery, and add discoveryClient to Spring Boot Admin Server.

There are two spring client Service_A, Service_B,
Service_A's health check url is /serviceA/health, Service_B's health check url is /serviceB/health,

Then how to define the different health url for different client?

The application.yml for admin service is:
```
server:
  port: 9001
  servlet:
    context-path: /admin

spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true
      register: true
      discovery:
        enabled: true
        healthCheckPath: /admin/actuator/health
        preferIpAddress: true
        query-passing: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
```
