### ISSUE TITLE
Problems with resource resolution in SBA 2.1.0 having server.servlet.context-path set

### ISSUE THREAD

**Issue by dickerpulli** [codecentric/spring-boot-admin#990]
With having server.servlet.context-path set the resource resolution doesn't work property with SBA 2.1.0 wich results in a currupted login-page and a white page after login.

This problem only occurs when I set server.servlet.context-path. After deleting this property everythings works fine.

![grafik](https://user-images.githubusercontent.com/1300393/47992521-67508000-e0ed-11e8-8442-b3552a2fc2d8.png)

**Comment by joshiste** [comment]
Just for local development (using `npm run watch`)?

**Comment by dickerpulli** [comment]
No, also in staging environment.

**Comment by dejan-mladenovski** [comment]
I also have the same problem on staging environment.

With version 2.0.4 and defined a `server.servlet.context-path=/demo-adminserver`  the generated base href was `<base href="/demo-adminserver/" />` and all assets, css and js files were defined as for example `<link="assets/css/sba-core.css" .. />` which will pull the resource from `http://hostname/demo-adminserver/assets/css/sba-core.css`. Now, the generated HTML template is `<base href="/" />` and all static resources start with `/`, which will pull the resources from `http://hostname/assets/css/sba-core.css` completely ignoring the context path.

**Comment by wtatum** [comment]
Seeing the same behavior with the (equivalent?) configuration option spring.boot.admin.contextPath. The index page (and presumably API) resolve from the specified context path (i.e. /sba) but the UI loads static assets using host relative paths instead of including the context path, causing the blank white page and lots of errors on the console.


> GET http://localhost:8080/assets/js/chunk-common.82a7af35.js net::ERR_ABORTED
> sba:1 GET http://localhost:8080/assets/js/chunk-vendors.1df687d0.js net::ERR_ABORTED
> sba:1 GET http://localhost:8080/assets/css/chunk-common.9808b72e.css net::ERR_ABORTED
> sba:1 GET http://localhost:8080/assets/css/sba-core.360886fb.css net::ERR_ABORTED
> sba:1 GET http://localhost:8080/assets/js/sba-core.7dfee25c.js net::ERR_ABORTED
> sba:9 GET http://localhost:8080/assets/js/chunk-vendors.1df687d0.js net::ERR_ABORTED
> sba:9 GET http://localhost:8080/assets/js/chunk-common.82a7af35.js net::ERR_ABORTED
> sba:9 GET http://localhost:8080/assets/js/sba-core.7dfee25c.js net::ERR_ABORTED

**Comment by dheid** [comment]
👍

**Comment by joshiste** [comment]
> Some for me. This is critical, because usually one would deploy the admin ui to a tomcat webserver, where the servlet path is derived from the application filename

I've currently very limited time to do a fix. You can stick to the 2.0.x server until then - the api for sba-client/-server is up- and downwards compatible

**Comment by sddakoty** [comment]
I can confirm the 2.1.0 client works with 2.0.4 server. thanks!

**Comment by dickerpulli** [comment]
Fix provided at https://github.com/codecentric/spring-boot-admin/pull/997

**Comment by dotpanic** [comment]
The fix in 2.1.1 is not working on my side. With the following configuration:

![image](https://user-images.githubusercontent.com/10357940/48341870-8bbcd700-e66e-11e8-97d0-30fd508f4ede.png)

The base href is generated as followed:

![image](https://user-images.githubusercontent.com/10357940/48341853-7ba4f780-e66e-11e8-83e8-3a5fb8343061.png)

Client and server has been updated to v2.1.1

**Comment by joshiste** [comment]
Could you post your complete config?

**Comment by dotpanic** [comment]
I'm sorry, the previous error was on my side (wrong docker container deployment).

The href is now filled with a base URL:

`<base href="http://xxx.com/sba/">`

But I now get some Mixed Content errors in browser:

![image](https://user-images.githubusercontent.com/10357940/48345102-5b2d6b00-e677-11e8-98a9-bd01d6d7b370.png)

The main page is served via HTTPS and so the base href should be set to:

`<base href="https://xxx.com/sba/">`

I can't understand if it's a Spring Boot or Spring Boot Admin issue.

Here is my server configuration; 

```
server:
  port: 4040
spring:
  security:
    user:
      name: admin
      password: secret
  output:
    ansi:
      enabled: never
  boot:
    admin:
      context-path: /sba

# Spring Actuator
management:
  server:
    port: 9002
    address: localhost
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /sba/actuator
    enabled: true
    logfile:
      external-file: log/current-instance.log
    health:
      show-details: always
```
